"""Precomputed MIDI velocity → perceptual loudness lookup table.

Generated by running:
    python examples/calibrate_velocity.py

The table maps MIDI velocity (1–127) to a normalized loudness value in [0, 1]
based on the RMS amplitude measured from FluidSynth. This lets the RL reward
operate in perceptual loudness space rather than raw velocity number space.

Usage::

    calib = VelocityCalibration.load()
    loudness = calib[64]          # float in [0, 1]
    reward   = calib.reward(achieved_vel=70, target_vel=64)  # float in [-1, 0]
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

_DEFAULT_NPZ = Path(__file__).parent / "velocity_calibration.npz"


class VelocityCalibration:
    """Lookup table: MIDI velocity (1–127) → normalized loudness (0–1).

    Attributes:
        table: ndarray of shape (127,) where table[i] is the loudness for
               MIDI velocity i+1. Values are in [0, 1].
    """

    def __init__(self, table: np.ndarray) -> None:
        assert table.shape == (127,), f"Expected shape (127,), got {table.shape}"
        self.table = table.astype(np.float64)

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    @classmethod
    def load(cls, path: Path | str = _DEFAULT_NPZ) -> "VelocityCalibration":
        """Load from a .npz file produced by calibrate_velocity.py."""
        data = np.load(path)
        rms_fitted = data["rms_fitted"]   # shape (127,), index 0 = velocity 1
        rms_max = rms_fitted.max()
        if rms_max == 0:
            raise ValueError("Calibration RMS values are all zero.")
        table = np.clip(rms_fitted / rms_max, 0.0, 1.0)
        return cls(table)

    # ------------------------------------------------------------------
    # Core lookup
    # ------------------------------------------------------------------

    def __getitem__(self, velocity: int) -> float:
        """Return normalized loudness for a MIDI velocity (1–127)."""
        idx = int(np.clip(velocity - 1, 0, 126))
        return float(self.table[idx])

    def loudness(self, velocity: int | float) -> float:
        """Return normalized loudness for a MIDI velocity (1–127)."""
        return self[int(round(velocity))]

    # ------------------------------------------------------------------
    # RL reward
    # ------------------------------------------------------------------

    def reward(self, achieved_vel: int | float, target_vel: int | float) -> float:
        """Squared loudness error in [-1, 0].

        Returns -(loudness(achieved) - loudness(target))^2.
        Zero means perfect loudness match; -1 is the worst possible error
        (e.g., silent vs. full-volume).
        """
        delta = self.loudness(achieved_vel) - self.loudness(target_vel)
        return -float(delta * delta)
