"""Precomputed MIDI velocity → perceptual loudness lookup table.

Generated by running:
    python examples/calibrate_velocity.py

The table maps MIDI velocity (1–127) to a normalized loudness value in [0, 1]
based on the RMS amplitude measured from FluidSynth. This lets the RL reward
operate in perceptual loudness space rather than raw velocity number space.

Usage::

    calib = VelocityCalibration.load()
    loudness = calib[64]          # float in [0, 1]
    reward   = calib.reward(achieved_vel=70, target_vel=64)  # float in [-1, 0]
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

_DEFAULT_NPZ = Path(__file__).parent / "velocity_calibration.npz"


class VelocityCalibration:
    """Lookup table: MIDI velocity (1–127) → normalized loudness.

    Two scales are available:
        table:    linear RMS amplitude, normalized to [0, 1].
        table_db: dB-scale loudness (20*log10(rms)), normalized to [0, 1].
                  Matches human perception more closely; roughly uniform
                  gradient across the full velocity range.

    Attributes:
        table:    ndarray (127,) — linear RMS loudness, index 0 = velocity 1.
        table_db: ndarray (127,) — dB loudness, same indexing.
    """

    def __init__(self, table: np.ndarray, table_db: np.ndarray) -> None:
        assert table.shape == (127,)
        assert table_db.shape == (127,)
        self.table = table.astype(np.float64)
        self.table_db = table_db.astype(np.float64)

    # ------------------------------------------------------------------
    # Construction
    # ------------------------------------------------------------------

    @classmethod
    def load(cls, path: Path | str = _DEFAULT_NPZ) -> "VelocityCalibration":
        """Load from a .npz file produced by calibrate_velocity.py."""
        data = np.load(path)
        rms_fitted = data["rms_fitted"]   # shape (127,), index 0 = velocity 1
        rms_max = rms_fitted.max()
        if rms_max == 0:
            raise ValueError("Calibration RMS values are all zero.")
        table = np.clip(rms_fitted / rms_max, 0.0, 1.0)

        # dB scale: 20*log10(rms), normalized so that velocity=127 → 1.0
        _EPS = 1e-9
        db = 20.0 * np.log10(np.clip(rms_fitted, _EPS, None))
        db_min, db_max = db.min(), db.max()
        table_db = (db - db_min) / (db_max - db_min)

        return cls(table, table_db)

    # ------------------------------------------------------------------
    # Core lookup
    # ------------------------------------------------------------------

    def _idx(self, velocity: int | float) -> int:
        return int(np.clip(int(round(float(velocity))) - 1, 0, 126))

    def __getitem__(self, velocity: int) -> float:
        """Return linear RMS loudness for a MIDI velocity (1–127)."""
        return float(self.table[self._idx(velocity)])

    def loudness(self, velocity: int | float) -> float:
        """Return linear RMS loudness for a MIDI velocity (1–127)."""
        return float(self.table[self._idx(velocity)])

    def loudness_db(self, velocity: int | float) -> float:
        """Return dB-normalized loudness for a MIDI velocity (1–127).

        Uses 20*log10(rms), normalized to [0, 1]. Matches human perception
        more closely than the linear scale — gradient is roughly uniform
        across the full velocity range.
        """
        return float(self.table_db[self._idx(velocity)])

    # ------------------------------------------------------------------
    # RL reward
    # ------------------------------------------------------------------

    def reward(self, achieved_vel: int | float, target_vel: int | float) -> float:
        """Squared dB-loudness error in [-1, 0].

        Returns -(loudness_db(achieved) - loudness_db(target))^2.
        Zero means perfect loudness match; -1 is the worst possible error.
        Uses the dB scale for perceptually uniform gradient.
        """
        delta = self.loudness_db(achieved_vel) - self.loudness_db(target_vel)
        return -float(delta * delta)
